# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "About"
  url = "#about"
  weight = 10

[[main]]
  name = "Courses"
  weight = 30
  url = "#slider"

[[main]]
  name = "Introduction to Programming in C"
  parent = "Courses"
  weight = 31
  url = "/salon"

[[main]]
  name = "Algorithms and Programming in C++"
  parent = "Courses"
  weight = 32
  url = "/cpp"

[[main]]
  name = "Machine Learning in R & Python"
  parent = "Courses"
  weight = 33
  url = "/ml"

[[main]]
  name = "Reinforcement Learning in Python"
  parent = "Courses"
  weight = 34
  url = "/rl"

[[main]]
  name = "Posts"
  url = "#posts"
  weight = 40

[[main]]
  name = "Videos"
  url = "#videos"
  weight = 41

[[main]]
  name = '''Teaching
  Assistants'''
  url = "#ta"
  weight = 50


# [[main]]
#   name = "Tools"
#   url = "#partners"
#   weight = 60
#
# [[main]]
#   name = "Tags"
#   url = "#rare-eye-diseases"
#   weight = 70

[[main]]
  name = "Contact"
  url = "#contact"
  weight = 200
