# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "About"
  url = "#about"
  weight = 10

[[main]]
  name = "Projects"
  weight = 30 
  url = "#slider"  
  
[[main]]
  name = "Yuanyou Salon"
  parent = "Projects"
  weight = 31 
  url = "/salon"

[[main]]
  name = "Yuanyou Aid"
  parent = "Projects"
  weight = 32
  url = "/aid"    

[[main]]
  name = "Yuanyou Connect"
  parent = "Projects"
  weight = 33
  url = "/connect"   
   
[[main]]
  name = "Yuanyou Wiki"
  parent = "Projects"
  weight = 34
  url = "/wiki" 

[[main]]
  name = "News"
  url = "#news"
  weight = 40  

[[main]]
  name = "Videos"
  url = "#videos"
  weight = 41  

#[[main]]
#  name = "Posts"
#  url = "#posts"
#  weight = 30

#[[main]]
#  name = "Rare Eye Diseases in China"
#  url = "#rare_eye_diseases_in_china"
#  weight = 40

#[[main]]
#  name = "History"
#  url = "#history"
#  weight = 50  
  

[[main]]
  name = "Volunteers"
  url = "#volunteers"
  weight = 50 


[[main]]
  name = "Partners"
  url = "#partners"
  weight = 60    

[[main]]
  name = "Rare Eye Diseases"
  url = "#rare-eye-diseases"
  weight = 70 
  
[[main]]
  name = "Contact"
  url = "#contact"
  weight = 200
