# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Qui sommes nous"
  url = "#about"
  weight = 10

[[main]]
  name = "Projects"
  weight = 30
  url = ""

[[main]]
  name = "Sallon de Yuanyou "
  parent = "Projects"
  weight = 31
  url = "../salon"

[[main]]
  name = "Aider par Yuanyou"
  parent = "Projects"
  weight = 32
  url = "../aid"

[[main]]
  name = "Connecter par Yuanyou"
  parent = "Projects"
  weight = 33
  url = "../connect"

[[main]]
  name = "Wiki de Yuanyou"
  parent = "Projects"
  weight = 34
  url = "../wiki"

#[[main]]
#  name = "Actualités"
#  url = "#posts"
#  weight = 40

#[[main]]
#  name = "Histoire"
#  url = "#history"
#  weight = 50

#[[main]]
#  name = "Partenaires"
#  url = "#partners"
#  weight = 60

[[main]]
  name = "Nous Contacter"
  url = "#contact"
  weight = 100
