name: ccpshu

on:
  push:
    branches:
    - master

jobs:
  build-deploy:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@master
      # with:
      #   submodules: true

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.85.0'
        extended: true

    - name: Build
      run: hugo --baseURL=https://cppshu.github.io

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v2.5.0
      with:
        github_token: ${{ secrets.PERSONAL_TOKEN }}
        deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        publish_branch: gh-pages
        publish_dir: ./public
